version: "3.1"

services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/var/www/html/

  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  db:
    image: mysql:5.6
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 4306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example